version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "nl-design-system/kernteam-dependabot"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "nl-design-system/kernteam-dependabot"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "nl-design-system/kernteam-dependabot"
