version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'Europe/Amsterdam'
      time: '09:00'
    reviewers:
      - 'nl-design-system/kernteam-dependabot'
